name: setti
description: Setti – simplify your app's configuration with declarative settings.
version: 0.1.0
# repository: https://github.com/my_org/my_repo
# issue_tracker:
# homepage:
# documentation:
# topics:
# funding:

environment:
  sdk: '>=3.0.0 <4.0.0'

# Add regular dependencies here.
dependencies:
  ini: ^2.1.0
  meta: ^1.16.0
  path: ^1.9.1

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
  mockito: ^5.4.4
  build_runner: ^2.4.0
  build_web_compilers: ^4.0.4
